FROM nginx:alpine

ARG PB_VERSION=0.22.20

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN apk add --no-cache \
    unzip \
    ca-certificates

ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_arm64.zip /tmp/pb.zip

RUN unzip /tmp/pb.zip -d /pb/

COPY ./pb_hooks /pb/pb_hooks

CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090"]


EXPOSE 80


